# Generated by Django 5.1.2 on 2024-11-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_primer_lugar_evento_segundo_lugar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='premio_primer_lugar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='evento',
            name='premio_segundo_lugar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='evento',
            name='premio_tercer_lugar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
