# Generated by Django 5.1.2 on 2024-11-30 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0004_evento_premio_primer_lugar_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="tipo_evento",
            field=models.CharField(
                choices=[
                    ("grande", "Evento Grande"),
                    ("comunitario", "Torneo Comunitario"),
                ],
                default="grande",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_participante", models.PositiveIntegerField()),
                ("fecha_inscripcion", models.DateTimeField(auto_now_add=True)),
                (
                    "torneo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to="eventos.evento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["numero_participante"],
                "unique_together": {("torneo", "usuario")},
            },
        ),
    ]
