# Generated by Django 5.1.2 on 2024-11-30 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0005_evento_tipo_evento_inscripcion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="tipo_evento",
        ),
        migrations.CreateModel(
            name="TorneoComunitario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("fecha", models.DateField()),
                ("contenido", models.TextField()),
                (
                    "modalidad",
                    models.CharField(
                        choices=[("presencial", "Presencial"), ("online", "Online")],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_torneo",
                    models.CharField(
                        choices=[
                            ("single_elimination", "Eliminación Simple"),
                            ("double_elimination", "Eliminación Doble"),
                            ("round_robin", "Round Robin"),
                        ],
                        default="single_elimination",
                        max_length=30,
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="torneos/"),
                ),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="torneos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Inscripcion",
        ),
    ]
