# Generated by Django 5.1.2 on 2024-11-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0006_remove_evento_tipo_evento_torneocomunitario_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TorneoComunitario",
        ),
    ]
