# Generated by Django 5.1.2 on 2024-11-30 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0007_delete_torneocomunitario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TorneoComunitario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("fecha", models.DateField()),
                (
                    "tipo_torneo",
                    models.CharField(
                        choices=[("presencial", "Presencial"), ("online", "Online")],
                        default="online",
                        max_length=10,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="torneos/"),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
