# Generated by Django 5.1.2 on 2024-12-01 00:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0008_torneocomunitario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="torneocomunitario",
            name="autor",
        ),
        migrations.AddField(
            model_name="torneocomunitario",
            name="bracket_generado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="torneocomunitario",
            name="organizador",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="torneos_organizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="InscripcionTorneo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inscripcion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "torneo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventos.torneocomunitario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="torneocomunitario",
            name="participantes",
            field=models.ManyToManyField(
                related_name="torneos_inscritos",
                through="eventos.InscripcionTorneo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marcador_jugador1", models.IntegerField(default=0)),
                ("marcador_jugador2", models.IntegerField(default=0)),
                ("ronda", models.IntegerField()),
                (
                    "ganador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ganador_match",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jugador1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jugador1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jugador2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jugador2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "torneo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventos.torneocomunitario",
                    ),
                ),
            ],
        ),
    ]
