# Generated by Django 5.1.2 on 2024-12-01 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0009_remove_torneocomunitario_autor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscripciontorneo",
            name="torneo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscripciones",
                to="eventos.torneocomunitario",
            ),
        ),
    ]
