# Generated by Django 5.1.2 on 2024-12-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0010_alter_inscripciontorneo_torneo"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="fase",
            field=models.CharField(
                choices=[
                    ("1ra", "Primera Ronda"),
                    ("2da", "Segunda Ronda"),
                    ("Final", "Final"),
                ],
                default="default",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
