# Generated by Django 5.1.2 on 2024-12-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0012_remove_match_fase"),
    ]

    operations = [
        migrations.AddField(
            model_name="torneocomunitario",
            name="direccion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
