# Generated by Django 5.1.2 on 2024-11-22 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='respuesta_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='noticias.noticia'),
        ),
    ]
