"""
Django settings for prueba project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path


SESSION_COOKIE_AGE = 3600  # 1 hora
SESSION_SAVE_EVERY_REQUEST = True
#Configuraciones de paypal
PAYPAL_MODE = 'sandbox'  # 'sandbox' para pruebas, 'live' para producción
PAYPAL_CLIENT_ID = 'AfhxUcCCzA3JGdj762s7rg1scyxJx-agBF4n4S06rxOSzWH5XMcwMiX6DKXkkRtaUmAc0ZiKUslLNXc5'
PAYPAL_CLIENT_SECRET = 'EPuuTW6l6xy6YopXgpW_CZ2Xv9W0zidKQxZDTsAuu5st5l865MZe9ZsRvcw0xPwEORiRGSxglgTcVyM0'

# Configuración de sesiones
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # La sesión se cierra al cerrar el navegador
SESSION_COOKIE_AGE = 3600  # 1 hora de inactividad (3600 segundos)
SESSION_SAVE_EVERY_REQUEST = True  # Renueva la sesión en cada petición


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-)5#$d$w-ta14wxvoj3a0w7de_ngti-k3!c&_pnu%#jbhlm7-i6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["yourdomain.com", "localhost", "127.0.0.1"]

import django_heroku

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django_extensions",
    "noticias.apps.NoticiasConfig",
    "sass_processor",
    "eventos.apps.EventosConfig",
    "crispy_forms",
    "polls.apps.PollsConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

AUTH_USER_MODEL = "polls.CustomUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
CRISPY_TEMPLATE_PACK = "bootstrap5"

ROOT_URLCONF = "prueba.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "prueba.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "es-mx"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Configuraciones de las URLs de redirección post-login/logout
LOGIN_REDIRECT_URL = "/"  # Redirigir al home después de iniciar sesión
LOGOUT_REDIRECT_URL = "/"  # Redirigir al home después de cerrar sesión

JAZZMIN_SETTINGS = {
    "site_title": "Mi Proyecto Django",
    "site_header": "Administración de Juegos de Lucha",
    "site_brand": "FightingGamesApp",
    "welcome_sign": "Bienvenido al panel de administración",
    "copyright": "2024 Mi Nombre o Mi Empresa",
    "search_model": "auth.User",
    "show_ui_builder": True,  # Si deseas usar el diseñador de UI de Jazzmin
    "navigation_expanded": True,  # Para que el menú de navegación esté expandido
     "topmenu_links": [{"name": "Volver a la pagina.", "url":"polls:"}]
}
