# Generated by Django 5.1.2 on 2024-11-12 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre o etiqueta del combo (por ejemplo, 'Bread and Butter Combo')", max_length=100)),
                ('movimientos', models.TextField(help_text="Lista de movimientos en formato secuencial (ej. 'LP, MP, HP')")),
                ('daño', models.IntegerField(blank=True, help_text='Cantidad de daño que hace el combo', null=True)),
                ('dificultad', models.CharField(choices=[('Fácil', 'Fácil'), ('Intermedio', 'Intermedio'), ('Difícil', 'Difícil')], help_text='Dificultad del combo', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o contexto del combo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó o compartió el combo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='polls.personaje')),
            ],
            options={
                'ordering': ['personaje', 'dificultad', '-fecha_creacion'],
            },
        ),
    ]
