# Generated by Django 5.1.2 on 2024-11-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='video_demo_url',
            field=models.URLField(blank=True, help_text='URL a un video de demostración', null=True),
        ),
    ]
