# Generated by Django 5.1.2 on 2024-11-12 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_combo_video_demo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('damage', models.IntegerField()),
                ('startup_frames', models.IntegerField()),
                ('active_frames', models.IntegerField()),
                ('recovery_frames', models.IntegerField()),
                ('block_advantage', models.IntegerField()),
                ('hit_advantage', models.IntegerField()),
                ('knockdown', models.BooleanField(default=False)),
                ('video_demo_url', models.URLField(blank=True, null=True)),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_data', to='polls.personaje')),
            ],
        ),
    ]
