# Generated by Django 5.1.2 on 2024-11-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='publisher',
            field=models.TextField(blank=True),
        ),
    ]
