# Generated by Django 5.1.2 on 2024-11-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_juego_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='polls/css/images/default.png', null=True, upload_to='avatars/'),
        ),
    ]
