# Generated by Django 5.1.2 on 2024-11-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_combo_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combo',
            old_name='file',
            new_name='video',
        ),
    ]
