# Generated by Django 5.1.2 on 2024-11-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_file_combo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='framedata',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='frameData/'),
        ),
    ]
