# Generated by Django 5.1.2 on 2024-11-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_framedata_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framedata',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='frameData/'),
        ),
    ]
