# Generated by Django 5.1.2 on 2024-11-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_framedata_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
