# Generated by Django 5.1.2 on 2024-11-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_customuser_puntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/'),
        ),
    ]
