# Generated by Django 5.1.2 on 2024-11-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framedata',
            name='imagen',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('admin', 'Admin'), ('redactor', 'Redactor')], default='normal', max_length=10),
        ),
    ]
