# Generated by Django 5.1.2 on 2024-11-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_framedata_imagen_customuser_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
