# Generated by Django 5.1.2 on 2024-11-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
