# Generated by Django 5.1.2 on 2024-11-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='juegos_competencia',
        ),
        migrations.AddField(
            model_name='customuser',
            name='juegos_competencia',
            field=models.ManyToManyField(blank=True, to='polls.juego'),
        ),
    ]
