# Generated by Django 5.1.2 on 2024-11-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_rolechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='descripcion_strategy',
            field=models.TextField(blank=True),
        ),
    ]
