# Generated by Django 5.1.2 on 2024-11-25 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_personaje_descripcion_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tacticas_generales', models.JSONField(blank=True, default=list)),
                ('posicionamiento_en_el_equipo', models.JSONField(blank=True, default=list)),
                ('block_string', models.JSONField(blank=True, default=list)),
                ('oki', models.JSONField(blank=True, default=list)),
                ('tips_y_trucos', models.JSONField(blank=True, default=list)),
                ('luchando_en_contra', models.JSONField(blank=True, default=list)),
                ('personaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estrategia', to='polls.personaje')),
            ],
        ),
    ]
