# Generated by Django 5.1.2 on 2024-11-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_estrategia'),
    ]

    operations = [
        migrations.AddField(
            model_name='framedata',
            name='imagen',
            field=models.ImageField(null=True, upload_to='refencia/'),
        ),
    ]
