# Generated by Django 5.1.2 on 2024-11-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_framedata_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framedata',
            name='active_frames',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='framedata',
            name='block_advantage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='framedata',
            name='damage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='framedata',
            name='hit_advantage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='framedata',
            name='recovery_frames',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='framedata',
            name='startup_frames',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
