# Generated by Django 5.1.2 on 2024-11-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_alter_framedata_active_frames_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='enlace_oficial',
            field=models.TextField(blank=True),
        ),
    ]
