# Generated by Django 5.1.2 on 2024-11-26 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_juego_enlace_oficial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_discord', models.URLField(blank=True, null=True)),
                ('hashtag_twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='polls.personaje')),
            ],
        ),
    ]
