# Generated by Django 5.1.2 on 2024-11-27 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_recurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glosario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('juego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glosarios', to='polls.juego')),
            ],
        ),
    ]
