# Generated by Django 5.1.2 on 2024-11-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_glosario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glosario',
            name='juego',
        ),
        migrations.AddField(
            model_name='glosario',
            name='juegos',
            field=models.ManyToManyField(blank=True, related_name='glosarios', to='polls.juego'),
        ),
    ]
