# Generated by Django 5.1.2 on 2024-11-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_remove_glosario_juego_glosario_juegos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glosario',
            old_name='juegos',
            new_name='juego',
        ),
    ]
