# Generated by Django 5.1.2 on 2024-11-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0028_rename_juegos_glosario_juego"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaje",
            name="visitas",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
