# Generated by Django 5.1.2 on 2024-11-28 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0029_personaje_visitas"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonajeVisita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_visita", models.DateTimeField(auto_now_add=True)),
                (
                    "juego",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juego_visitas",
                        to="polls.juego",
                    ),
                ),
                (
                    "personaje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personaje_visitas",
                        to="polls.personaje",
                    ),
                ),
            ],
        ),
    ]
