# Generated by Django 5.1.2 on 2024-11-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0030_personajevisita"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("admin", "Admin"),
                    ("redactor", "Redactor"),
                    ("organizador", "Organizador"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
