# Generated by Django 5.1.2 on 2024-11-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0031_alter_customuser_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combo",
            name="daño",
        ),
        migrations.AddField(
            model_name="combo",
            name="dano",
            field=models.IntegerField(
                blank=True, help_text="Cantidad de dano que hace el combo", null=True
            ),
        ),
    ]
