# Generated by Django 5.1.2 on 2024-11-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0032_remove_combo_daño_combo_dano"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="dano",
            field=models.IntegerField(
                blank=True, help_text="Cantidad de daño que hace el combo", null=True
            ),
        ),
    ]
