# Generated by Django 5.1.2 on 2024-11-29 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0033_alter_combo_dano"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurso",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("combo", "Combo Avanzado"),
                    ("tech", "Tech de Defensa"),
                    ("guia", "Guía de Principiantes"),
                    ("comunidad", "Comunidad"),
                ],
                default="comunidad",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recurso",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recursos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recurso",
            name="descripcion",
            field=models.TextField(
                blank=True, help_text="Breve descripción del recurso"
            ),
        ),
        migrations.AddField(
            model_name="recurso",
            name="dislikes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recurso",
            name="enlace_video",
            field=models.URLField(
                blank=True, help_text="Enlace a YouTube o Twitter", null=True
            ),
        ),
        migrations.AddField(
            model_name="recurso",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
