# Generated by Django 5.1.2 on 2024-11-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0034_recurso_categoria_recurso_creado_por_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurso",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("Combo", "Combo Avanzado"),
                    ("Tech", "Tech de Defensa"),
                    ("Guia", "Guía de Principiantes"),
                    ("Comunidad", "Comunidad"),
                ],
                default="comunidad",
                max_length=20,
            ),
        ),
    ]
