# Generated by Django 5.1.2 on 2024-11-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0035_alter_recurso_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="personajes_favoritos",
            field=models.ManyToManyField(
                blank=True, related_name="fans", to="polls.personaje"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="twitch_stream",
            field=models.URLField(
                blank=True, help_text="Enlace a tu canal de Twitch", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="videos_subidos",
            field=models.ManyToManyField(
                blank=True, related_name="creadores", to="polls.recurso"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="youtube_channel",
            field=models.URLField(
                blank=True, help_text="Enlace a tu canal de YouTube", null=True
            ),
        ),
        migrations.AlterField(
            model_name="recurso",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("Combo", "Combo Avanzado"),
                    ("Tech", "Tech de Defensa"),
                    ("Guia", "Guía de Principiantes"),
                    ("Comunidad", "Comunidad"),
                    ("video", "Video"),
                ],
                default="comunidad",
                max_length=20,
            ),
        ),
    ]
