# Generated by Django 5.1.2 on 2024-11-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0036_customuser_personajes_favoritos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="twitch_stream",
            field=models.CharField(
                blank=True,
                help_text="Ingresa solo Nick del canal",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="youtube_channel",
            field=models.CharField(
                blank=True,
                help_text="Ingresa solo el nick del canal",
                max_length=100,
                null=True,
            ),
        ),
    ]
