# Generated by Django 5.1.2 on 2024-11-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0037_alter_customuser_twitch_stream_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="twitch_stream",
            field=models.URLField(
                blank=True, help_text="Enlace a tu canal de Twitch", null=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="youtube_channel",
            field=models.URLField(
                blank=True, help_text="Enlace a tu canal de YouTube", null=True
            ),
        ),
    ]
