# Generated by Django 5.1.2 on 2024-12-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0040_customuser_musica_fondo_customuser_tema_perfil"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="imagen_fondo",
            field=models.ImageField(blank=True, null=True, upload_to="backgrounds/"),
        ),
    ]
